### ISSUE TITLE
weaviate withNearImage never hits

### ISSUE THREAD

**Issue by MattFelice** [weaviate/typescript-client#48]
So I have been trying for awhile now and I can't seem to get weaviate to hit any image when i use withNearImage .

When I remove withNearImage it will give me a image back and writing it to the disk is the same as when i was inputting. Data isn't getting lost.

Lastly when I reuse the same image I just get back when I run without  withNearImage it still won't hit. Not sure what is wrong with my test script.

```typescript
import { readFileSync, writeFileSync } from "fs";
import weaviate from 'weaviate-ts-client';

const test = Buffer.from(readFileSync(__dirname + '/test.jpg')).toString('base64');
writeFileSync(__dirname + '/test_out.jpg', Buffer.from(test, 'base64'));

console.log(test.length);

const weaviateClient = weaviate.client({
    scheme: 'http',
    host: process.env.WEAVIATE_HOST || 'localhost',
});

const run = async () => {
    try {
        const resImage = await weaviateClient.graphql.get()
        .withClassName('ImageSearch')
        .withFields('image')
        .withNearImage({image: test})
        .withLimit(1)
        .do();

        console.log(resImage.data.Get['ImageSearch'][0]);

        const result = resImage.data.Get['ImageSearch'][0].image;
        writeFileSync(__dirname + '/result.jpg', Buffer.from(result, 'base64'));
    } catch (e) {
        console.error(e);
        process.exit(1);
    }
}

run();
```

here is my error I get back when i run my script
```
yarn run v1.22.19
warning package.json: No license field
$ /app/node_modules/.bin/ts-node-dev src/test.ts
[INFO] 14:22:47 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.0.4)
121232
TypeError: Cannot read properties of undefined (reading 'image')
    at /app/src/test.ts:26:71
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/test.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MattFelice** [comment]
My bad. Miss spelled `img2vec-neural` in my `moduleConfig`

Was (aka bad version)
```
moduleConfig: {
            'im2vec-neural': {
                'imageFields': [
                    'image'
                ]
            }
        }
```

Needs to be
```
moduleConfig: {
            'img2vec-neural': {
                'imageFields': [
                    'image'
                ]
            }
        }
        ```
